TEAM_COLORS = {
    "Red Bull Racing": {"hex": "#3671C6", "name": "Blue"},
    "McLaren": {"hex": "#FF8000", "name": "Papaya"},
    "Ferrari": {"hex": "#E8002D", "name": "Red"},
    "Mercedes": {"hex": "#27F4D2", "name": "Teal"},
    "Aston Martin": {"hex": "#229971", "name": "Green"},
    "Alpine": {"hex": "#FF87BC", "name": "Pink"},
    "Haas F1 Team": {"hex": "#B6BABD", "name": "Silver"},
    "RB": {"hex": "#6692FF", "name": "Blue"},
    "Williams": {"hex": "#64C4FF", "name": "Light Blue"},
    "Kick Sauber": {"hex": "#52E252", "name": "Green"},
}

DRIVERS_2025 = {
    1: {"abbreviation": "VER", "name": "Max Verstappen", "team": "Red Bull Racing"},
    4: {"abbreviation": "NOR", "name": "Lando Norris", "team": "McLaren"},
    16: {"abbreviation": "LEC", "name": "Charles Leclerc", "team": "Ferrari"},
    44: {"abbreviation": "HAM", "name": "Lewis Hamilton", "team": "Ferrari"},
    63: {"abbreviation": "RUS", "name": "George Russell", "team": "Mercedes"},
    81: {"abbreviation": "PIA", "name": "Oscar Piastri", "team": "McLaren"},
    14: {"abbreviation": "ALO", "name": "Fernando Alonso", "team": "Aston Martin"},
    18: {"abbreviation": "STR", "name": "Lance Stroll", "team": "Aston Martin"},
    10: {"abbreviation": "GAS", "name": "Pierre Gasly", "team": "Alpine"},
    31: {"abbreviation": "OCO", "name": "Esteban Ocon", "team": "Haas F1 Team"},
    23: {"abbreviation": "ALB", "name": "Alexander Albon", "team": "Williams"},
    55: {"abbreviation": "SAI", "name": "Carlos Sainz", "team": "Williams"},
    22: {"abbreviation": "TSU", "name": "Yuki Tsunoda", "team": "RB"},
    30: {"abbreviation": "LAW", "name": "Liam Lawson", "team": "Red Bull Racing"},
    87: {"abbreviation": "DRU", "name": "Jack Doohan", "team": "Alpine"},
    27: {"abbreviation": "HUL", "name": "Nico Hulkenberg", "team": "Kick Sauber"},
    12: {"abbreviation": "BOR", "name": "Gabriel Bortoleto", "team": "Kick Sauber"},
    38: {"abbreviation": "BEA", "name": "Oliver Bearman", "team": "Haas F1 Team"},
    6: {"abbreviation": "HAD", "name": "Isack Hadjar", "team": "RB"},
    43: {"abbreviation": "ANT", "name": "Kimi Antonelli", "team": "Mercedes"},
}

CIRCUITS_2025 = {
    "bahrain": {"name": "Bahrain International Circuit", "country": "Bahrain", "city": "Sakhir"},
    "jeddah": {"name": "Jeddah Corniche Circuit", "country": "Saudi Arabia", "city": "Jeddah"},
    "albert_park": {"name": "Albert Park Circuit", "country": "Australia", "city": "Melbourne"},
    "shanghai": {"name": "Shanghai International Circuit", "country": "China", "city": "Shanghai"},
    "miami": {"name": "Miami International Autodrome", "country": "USA", "city": "Miami"},
    "imola": {"name": "Autodromo Enzo e Dino Ferrari", "country": "Italy", "city": "Imola"},
    "monaco": {"name": "Circuit de Monaco", "country": "Monaco", "city": "Monte Carlo"},
    "barcelona": {"name": "Circuit de Barcelona-Catalunya", "country": "Spain", "city": "Barcelona"},
    "villeneuve": {"name": "Circuit Gilles Villeneuve", "country": "Canada", "city": "Montreal"},
    "red_bull_ring": {"name": "Red Bull Ring", "country": "Austria", "city": "Spielberg"},
    "silverstone": {"name": "Silverstone Circuit", "country": "UK", "city": "Silverstone"},
    "spa": {"name": "Circuit de Spa-Francorchamps", "country": "Belgium", "city": "Spa"},
    "hungaroring": {"name": "Hungaroring", "country": "Hungary", "city": "Budapest"},
    "zandvoort": {"name": "Circuit Zandvoort", "country": "Netherlands", "city": "Zandvoort"},
    "monza": {"name": "Autodromo Nazionale Monza", "country": "Italy", "city": "Monza"},
    "baku": {"name": "Baku City Circuit", "country": "Azerbaijan", "city": "Baku"},
    "marina_bay": {"name": "Marina Bay Street Circuit", "country": "Singapore", "city": "Singapore"},
    "suzuka": {"name": "Suzuka International Racing Course", "country": "Japan", "city": "Suzuka"},
    "losail": {"name": "Losail International Circuit", "country": "Qatar", "city": "Lusail"},
    "americas": {"name": "Circuit of the Americas", "country": "USA", "city": "Austin"},
    "rodriguez": {"name": "Autodromo Hermanos Rodriguez", "country": "Mexico", "city": "Mexico City"},
    "interlagos": {"name": "Autodromo Jose Carlos Pace", "country": "Brazil", "city": "Sao Paulo"},
    "vegas": {"name": "Las Vegas Street Circuit", "country": "USA", "city": "Las Vegas"},
    "yas_marina": {"name": "Yas Marina Circuit", "country": "UAE", "city": "Abu Dhabi"},
}

TIRE_COMPOUNDS = {
    "SOFT": {"color": "#E10600", "label": "S"},
    "MEDIUM": {"color": "#FDE047", "label": "M"},
    "HARD": {"color": "#FFFFFF", "label": "H"},
    "INTERMEDIATE": {"color": "#00FF7F", "label": "I"},
    "WET": {"color": "#22D3EE", "label": "W"},
}
