TEAM_COLORS = {
    "Red Bull Racing": {"hex": "#3671C6", "name": "Blue"},
    "McLaren": {"hex": "#FF8000", "name": "Papaya"},
    "Ferrari": {"hex": "#E8002D", "name": "Red"},
    "Mercedes": {"hex": "#27F4D2", "name": "Teal"},
    "Aston Martin": {"hex": "#229971", "name": "Green"},
    "Alpine": {"hex": "#0093CC", "name": "Blue"},
    "Haas": {"hex": "#B6BABD", "name": "Silver"},
    "Racing Bulls": {"hex": "#6692FF", "name": "Blue"},
    "Williams": {"hex": "#64C4FF", "name": "Light Blue"},
    "Audi": {"hex": "#00594F", "name": "Teal"},
    "Cadillac": {"hex": "#D4A96A", "name": "Gold"},
}

# 2026 grid — sourced from frontend/src/data/teams2026.ts
DRIVERS_2026 = {
    1: {"abbreviation": "NOR", "name": "Lando Norris", "team": "McLaren"},
    81: {"abbreviation": "PIA", "name": "Oscar Piastri", "team": "McLaren"},
    16: {"abbreviation": "LEC", "name": "Charles Leclerc", "team": "Ferrari"},
    44: {"abbreviation": "HAM", "name": "Lewis Hamilton", "team": "Ferrari"},
    33: {"abbreviation": "VER", "name": "Max Verstappen", "team": "Red Bull Racing"},
    6: {"abbreviation": "HAD", "name": "Isack Hadjar", "team": "Red Bull Racing"},
    63: {"abbreviation": "RUS", "name": "George Russell", "team": "Mercedes"},
    12: {"abbreviation": "ANT", "name": "Kimi Antonelli", "team": "Mercedes"},
    14: {"abbreviation": "ALO", "name": "Fernando Alonso", "team": "Aston Martin"},
    18: {"abbreviation": "STR", "name": "Lance Stroll", "team": "Aston Martin"},
    10: {"abbreviation": "GAS", "name": "Pierre Gasly", "team": "Alpine"},
    43: {"abbreviation": "COL", "name": "Franco Colapinto", "team": "Alpine"},
    23: {"abbreviation": "ALB", "name": "Alexander Albon", "team": "Williams"},
    55: {"abbreviation": "SAI", "name": "Carlos Sainz", "team": "Williams"},
    30: {"abbreviation": "LAW", "name": "Liam Lawson", "team": "Racing Bulls"},
    2: {"abbreviation": "LIN", "name": "Arvid Lindblad", "team": "Racing Bulls"},
    31: {"abbreviation": "OCO", "name": "Esteban Ocon", "team": "Haas"},
    87: {"abbreviation": "BEA", "name": "Oliver Bearman", "team": "Haas"},
    27: {"abbreviation": "HUL", "name": "Nico Hulkenberg", "team": "Audi"},
    5: {"abbreviation": "BOR", "name": "Gabriel Bortoleto", "team": "Audi"},
    77: {"abbreviation": "BOT", "name": "Valtteri Bottas", "team": "Cadillac"},
    11: {"abbreviation": "PER", "name": "Sergio Perez", "team": "Cadillac"},
}

CONSTRUCTORS_2026 = {
    "mclaren": {"name": "McLaren", "full_name": "McLaren-Mercedes", "color": "#FF8000", "engine": "Mercedes", "drivers": [1, 81]},
    "ferrari": {"name": "Ferrari", "full_name": "Scuderia Ferrari", "color": "#E8002D", "engine": "Ferrari", "drivers": [16, 44]},
    "red_bull": {"name": "Red Bull", "full_name": "Red Bull Racing-Ford", "color": "#3671C6", "engine": "Red Bull/Ford", "drivers": [33, 6]},
    "mercedes": {"name": "Mercedes", "full_name": "Mercedes-AMG Petronas", "color": "#27F4D2", "engine": "Mercedes", "drivers": [63, 12]},
    "aston_martin": {"name": "Aston Martin", "full_name": "Aston Martin Aramco-Honda", "color": "#229971", "engine": "Honda", "drivers": [14, 18]},
    "williams": {"name": "Williams", "full_name": "Williams-Mercedes", "color": "#64C4FF", "engine": "Mercedes", "drivers": [23, 55]},
    "alpine": {"name": "Alpine", "full_name": "Alpine-Mercedes", "color": "#0093CC", "engine": "Mercedes", "drivers": [10, 43]},
    "racing_bulls": {"name": "Racing Bulls", "full_name": "Racing Bulls-Red Bull Ford", "color": "#6692FF", "engine": "Red Bull/Ford", "drivers": [30, 2]},
    "haas": {"name": "Haas", "full_name": "Haas-Ferrari", "color": "#B6BABD", "engine": "Ferrari", "drivers": [31, 87]},
    "audi": {"name": "Audi", "full_name": "Audi F1 Team", "color": "#00594F", "engine": "Audi", "drivers": [27, 5]},
    "cadillac": {"name": "Cadillac", "full_name": "Cadillac F1 Team", "color": "#D4A96A", "engine": "Ferrari", "drivers": [77, 11]},
}

CIRCUITS_2025 = {
    "bahrain": {"name": "Bahrain International Circuit", "country": "Bahrain", "city": "Sakhir"},
    "jeddah": {"name": "Jeddah Corniche Circuit", "country": "Saudi Arabia", "city": "Jeddah"},
    "albert_park": {"name": "Albert Park Circuit", "country": "Australia", "city": "Melbourne"},
    "shanghai": {"name": "Shanghai International Circuit", "country": "China", "city": "Shanghai"},
    "miami": {"name": "Miami International Autodrome", "country": "USA", "city": "Miami"},
    "imola": {"name": "Autodromo Enzo e Dino Ferrari", "country": "Italy", "city": "Imola"},
    "monaco": {"name": "Circuit de Monaco", "country": "Monaco", "city": "Monte Carlo"},
    "barcelona": {"name": "Circuit de Barcelona-Catalunya", "country": "Spain", "city": "Barcelona"},
    "villeneuve": {"name": "Circuit Gilles Villeneuve", "country": "Canada", "city": "Montreal"},
    "red_bull_ring": {"name": "Red Bull Ring", "country": "Austria", "city": "Spielberg"},
    "silverstone": {"name": "Silverstone Circuit", "country": "UK", "city": "Silverstone"},
    "spa": {"name": "Circuit de Spa-Francorchamps", "country": "Belgium", "city": "Spa"},
    "hungaroring": {"name": "Hungaroring", "country": "Hungary", "city": "Budapest"},
    "zandvoort": {"name": "Circuit Zandvoort", "country": "Netherlands", "city": "Zandvoort"},
    "monza": {"name": "Autodromo Nazionale Monza", "country": "Italy", "city": "Monza"},
    "baku": {"name": "Baku City Circuit", "country": "Azerbaijan", "city": "Baku"},
    "marina_bay": {"name": "Marina Bay Street Circuit", "country": "Singapore", "city": "Singapore"},
    "suzuka": {"name": "Suzuka International Racing Course", "country": "Japan", "city": "Suzuka"},
    "losail": {"name": "Losail International Circuit", "country": "Qatar", "city": "Lusail"},
    "americas": {"name": "Circuit of the Americas", "country": "USA", "city": "Austin"},
    "rodriguez": {"name": "Autodromo Hermanos Rodriguez", "country": "Mexico", "city": "Mexico City"},
    "interlagos": {"name": "Autodromo Jose Carlos Pace", "country": "Brazil", "city": "Sao Paulo"},
    "vegas": {"name": "Las Vegas Street Circuit", "country": "USA", "city": "Las Vegas"},
    "yas_marina": {"name": "Yas Marina Circuit", "country": "UAE", "city": "Abu Dhabi"},
}

TIRE_COMPOUNDS = {
    "SOFT": {"color": "#E10600", "label": "S"},
    "MEDIUM": {"color": "#FDE047", "label": "M"},
    "HARD": {"color": "#FFFFFF", "label": "H"},
    "INTERMEDIATE": {"color": "#00FF7F", "label": "I"},
    "WET": {"color": "#22D3EE", "label": "W"},
}
